input_points_path: /Users/ldp/Downloads/TestPoint3.csv
v2_table_path: /Users/ldp/Downloads/gv2Centroids.parquet
reach_ids_path: /Users/ldp/Downloads/Reach_ID_3.csv
Geoglows_Hist_Path: /Users/ldp/Downloads/Geoglows_hist_3.csv
Master_SAR_dates_path: /Users/ldp/Documents/FIER/ImgDates/Sentinel1_Bounds_
SAR_dates_path: /Users/ldp/Downloads/SAR_dates_3b.parquet
flow_occurance_path: /Users/ldp/Downloads/flow_occurance_new_3.csv
master_dates_path: /Users/ldp/Downloads/master_dates_new_3.csv
return_period: 10

