input_points_path: /Users/ldp/Downloads/test_points.csv
v2_table_path: /Users/ldp/Downloads/gv2Centroids.parquet
reach_ids_path: /Users/ldp/Downloads/reach_ID.csv
Geoglows_Hist_Path: /Users/ldp/Downloads/Geoglows_hist.csv
SAR_dates_path: /Users/ldp/Downloads/SAR_dates.csv
flow_occurance_path: /Users/ldp/Downloads/flow_occurance_new.csv
master_dates_path: /Users/ldp/Downloads/master_dates_new.csv
return_period: 10

